name: build

on: [
  pull_request,
  push
]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3.5.3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3.4.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          java-package: jdk
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: setup node.js environment
        uses: actions/setup-node@v3.7.0

      - name: build backend
        run: ./gradlew build
      - name: build frontend
        run: |
          cd Radium
          npm install
          npm run build

      - name: capture backend build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: backend_artifacts
          path: build/libs/
      - name: capture frontend build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: frontend_artifacts
          path: Radium/dist
